export interface IConfig {
  PORT: string;
  API_URL: string;
  MONGO_URI: string;
  CLOUDINARY_API_KEY: string;
  CLOUDINARY_API_SECRET: string;
  CLOUDINARY_CLOUD_NAME: string;
  CLOUDINARY_CLOUD_PROFILEPICS_IMAGES_FOLDERNAME: string;
  CLOUDINARY_URL: string;
  SUPABASE_API_URL: string;
  SUPABASE_API_KEY: string;
  SUPABASE_BUCKET_NAME: string;
  SUPABASE_HELPER_KYCDOCUMENTS_PDFS_FOLDERNAME: string;
  SUPABASE_HELPER_IDENTIFICATIONCARD_PDFS_FOLDERNAME: string;
  SUPABASE_HELPER_ADDITIONAL_DOCUMENTS_PDFS_FOLDERNAME: string;
}
