interface Config {
  PORT: string;
  API_URL: string;
  MONGO_URI: string;
  CLOUDINARY_API_KEY: string;
  CLOUDINARY_API_SECRET: string;
  CLOUDINARY_CLOUD_NAME: string;
  CLOUDINARY_CLOUD_PROFILEPICS_IMAGES_FOLDERNAME: string;
  CLOUDINARY_URL: string;
  SUPABASE_API_URL: string;
  SUPABASE_API_KEY: string;
  SUPABASE_BUCKET_NAME: string;
  SUPABASE_HELPER_KYCDOCUMENTS_PDFS_FOLDERNAME: string;
  SUPABASE_HELPER_IDENTIFICATIONCARD_PDFS_FOLDERNAME: string;
  SUPABASE_HELPER_ADDITIONAL_DOCUMENTS_PDFS_FOLDERNAME: string;
}

function getEnvVar(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing environment variable: ${name}`);
  }
  return value;
}

export const config: Config = {
  PORT: getEnvVar("PORT"),
  API_URL: getEnvVar("API_URL"),
  MONGO_URI: getEnvVar("MONGO_URI"),
  CLOUDINARY_API_KEY: getEnvVar("CLOUDINARY_API_KEY"),
  CLOUDINARY_API_SECRET: getEnvVar("CLOUDINARY_API_SECRET"),
  CLOUDINARY_CLOUD_NAME: getEnvVar("CLOUDINARY_CLOUD_NAME"),
  CLOUDINARY_URL: `cloudinary://${getEnvVar("CLOUDINARY_API_KEY")}:${getEnvVar(
    "CLOUDINARY_API_SECRET"
  )}@${getEnvVar("CLOUDINARY_CLOUD_NAME")}`,
  CLOUDINARY_CLOUD_PROFILEPICS_IMAGES_FOLDERNAME: getEnvVar(
    "CLOUDINARY_CLOUD_PROFILEPICS_IMAGES_FOLDERNAME"
  ),
  SUPABASE_API_URL: getEnvVar("SUPABASE_API_URL"),
  SUPABASE_API_KEY: getEnvVar("SUPABASE_API_KEY"),
  SUPABASE_BUCKET_NAME: getEnvVar("SUPABASE_BUCKET_NAME"),

  SUPABASE_HELPER_KYCDOCUMENTS_PDFS_FOLDERNAME: getEnvVar(
    "SUPABASE_HELPER_KYCDOCUMENTS_PDFS_FOLDERNAME"
  ),
  SUPABASE_HELPER_IDENTIFICATIONCARD_PDFS_FOLDERNAME: getEnvVar(
    "SUPABASE_HELPER_IDENTIFICATIONCARD_PDFS_FOLDERNAME"
  ),
  SUPABASE_HELPER_ADDITIONAL_DOCUMENTS_PDFS_FOLDERNAME: getEnvVar(
    "SUPABASE_HELPER_ADDITIONAL_DOCUMENTS_PDFS_FOLDERNAME"
  ),
};
